# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  Servor_1_to_waist:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  left_1_arm:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  left_2_arm:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  left_3_arm:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
